name: Ежедневное обновление Demonlist

on:
  schedule:
    - cron: '0 5 * * *' # Каждый день в 5 утра по UTC
  workflow_dispatch: # Кнопка для ручного запуска

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      # Шаг 1: Скачиваем код из твоего репозитория на временный сервер
      - name: Checkout repository
        uses: actions/checkout@v3

      # Шаг 2: Устанавливаем Python
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Шаг 3: Устанавливаем все нужные библиотеки
      - name: Install dependencies
        run: pip install -r requirements.txt

      # Шаг 4: Устанавливаем браузеры для Playwright
      - name: Install Playwright browsers and dependencies
        run: playwright install --with-deps

      # Шаг 5 (ИСПРАВЛЕНО): Запускаем наш главный скрипт
      - name: Run data scraper
        run: python update_data.py

      # Шаг 6 (ДОБАВЛЕНО): Автоматически коммитим и пушим обновленный файл данных
      - name: Commit and push if data changed
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore(auto): 🔄 Ежедневное обновление данных Demonlist"
          
          file_pattern: data/demonlist.json